- pkg/operator/targetcontroller/controller.go
- pkg/operator/targetcontroller/sync.go
- pkg/operator/targetcontroller/sync_test.go
When sync errors encountered, nothing is added to queue, so operator is stuck until operator pod refreshed.  This PR ensures resync upon error.
> Bug 1822943: return sync error to add to queue

- .gitignore
- Makefile
- go.mod
- go.sum
- manifests/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml
- vendor/github.com/openshift/build-machinery-go/go.mod
- vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
- vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
- vendor/modules.txt
Once telepresence has been installed (see the run-telepresence.sh script for instructions), `make telepresence` will replace the operator's pod with a local process that has access to the same environment as the pod. This can speed up development since iteration doesn't rely on image build/push/pull cycle. See https://telepresence.io for more details.
> Bug 1834852: Add make target to run operator with telepresence 

- manifests/0000_40_kube-storage-version-migrator-operator_01_storage_migration_crd.yaml
- manifests/0000_40_kube-storage-version-migrator-operator_01_storage_state_crd.yaml
When defining a CRD using the apiextensions.k8s.io/v1beta1 CustomResourceDefinition API, `preserveUnknownFields` defaults to `true`, which suppresses the publishing of the openapi validation schema.
> Bug 1809397: oc explain storagestates and storageversionmigrations with empty DESCRIPTION

- go.mod
- go.sum
- vendor/github.com/openshift/api/go.mod
- vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
- vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
- vendor/github.com/openshift/api/imageregistry/v1/types.go
- vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
- vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- vendor/github.com/openshift/api/operator/v1/types.go
- vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
- vendor/modules.txt
openshift/api#736 added restrictions for logLevel values. This PR vendors new openshift/api to get new CRDs.
> Bug 1878040: Add validation for logLevel

- images/ci/Dockerfile
Updating ose-cluster-kube-storage-version-migrator-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-kube-storage-version-migrator-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cluster-kube-storage-version-migrator-operator builder & base images to be consistent with ART

- bindata/kube-storage-version-migrator/deployment.yaml
- pkg/operator/assets/bindata.go
The migrator is always running and does not consume 100mc, which is against
our policy for out of the box components. The pod is still burstable
which does not prevent excess CPU from being consumed, but components are
not allowed to significantly overstate their steady state CPU. A future
alternative is for the operator to only run the migrator when necessary,
in which case the CPU and memory use can be increased to be consistent
with use during runtime.
/hold
while we review all the PRs together
> Bug 1920159: CPU request for migrator should not be higher than average use

- bindata/kube-storage-version-migrator/deployment.yaml
- pkg/operator/assets/bindata.go
Tolerate running migrator pod on master nodes. 
Ideally migrator should be running on a master node, but I'm not forcing it to with this PR due to past issues with the memory requirements that make it harder to schedule the migrator pod.
> Bug 1881938: migrator deployment doesn't tolerate masters 

- bindata/kube-storage-version-migrator/deployment.yaml
- bindata/kube-storage-version-migrator/namespace.yaml
- manifests/0000_40_kube-storage-version-migrator-operator_02_namespace.yaml
- manifests/0000_40_kube-storage-version-migrator-operator_07_deployment-ibm-cloud-managed.yaml
- manifests/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml
- pkg/operator/assets/bindata.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- go.mod
- go.sum
- vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
- vendor/k8s.io/apiserver/pkg/server/options/authentication.go
- vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
- vendor/modules.txt
This repository uses the delegated authentication which has been identified to contain a bug that increases the number of watch requests against the Kube API server.
We provided a temporary branch that contains a fix and switched this repository to that branch.
With this change, k8s.io/apiserver points to temporary-watch-reduction-patch-1.21 to pick up k/k/pull/101102
Feel free to remove it once the upstream PR merges and a new Z release is cut.
> Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout

- pkg/operator/targetcontroller/sync.go
>  11468x [     2.567ms] [404] /api/v1/namespaces/openshift-kube-storage-version-migrator-operator/configmaps/version-mapping [system:serviceaccount:openshift-kube-storage-version-migrator-operator:kube-storage-version-migrator-operator
This always returned empty string.  We don't have a meaningful operand version for the kube-storage-version-migrator.
> bug 1957908: stop reporting empty version

- README.md
Would be nice to have the README include (links to) collaboration notes and security issue reporting and all that.  But I'm not clear on what the operator maintainers want to use for that stuff, so this commit just brings over and tweaks a bit of text from [here][1] so folks wondering "what is this about?" don't have to think too hard.
[1]: https://github.com/openshift/kubernetes-kube-storage-version-migrator/blob/481bd04dbc78c29dad05deba0309e049fa26e4d9/USER_GUIDE.md#storage-version-migrator-in-a-nutshell
> README: Stub in brief purpose docs

- pkg/operator/starter.go
This is just a small typo fix.
/cc @sttts
> pkg/operator: fix typo starter clusteroperator

- pkg/operator/targetcontroller/sync.go
Add a `DefaultUpgradeable` condition, set to `True` to prevent the status controller from assigning `Unknown`.
> Bug 1928141: kube-storage-version-migrator constantly reporting type "Upgradeable" status Unknown

- pkg/operator/targetcontroller/sync.go
- pkg/operator/targetcontroller/sync_test.go
This is a cherry=pick of both #64 and #71.
> [release-4.9] Bug 2016176: kube-storage-version-migrator constantly reporting type "Upgradeable" status Unknown

- .ci-operator.yaml
I need to move this operator from `go1.14` to go `1.16`, otherwise it cannot consume updated deps when fixing bugs that depend on `go1.16` (specifically `client-go` uses the `io/fs` pkg from `go1.16`).
Plan:
1. introduce `.ci_operator.yaml` (this PR)
2. update ci-operator job to `build_root.from_repository: true`
3. update `.ci_operator.yaml` to use go1.16
4. finish the backport of #73
> [release-4.8] Bug 2022844: Extensive number of requests from storage version operator in cluster – Part 1

- bindata/kube-storage-version-migrator/deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
"objectRef": "openshift-kube-storage-version-migrator/pods/",
"pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"migrator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"migrator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"migrator\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container \"migrator\" must set …
```
> bindata: comply to restricted pod security level

- README.md
The trigger controller is not deployed by the operator so its feature shouldn't be advertised in the README.
> Fix operator doc in README

- bindata/kube-storage-version-migrator/deployment.yaml
Reverts #92 > ; tracked by [OCPBUGS-18125](https://issues.redhat.com/browse/OCPBUGS-18125)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This change has broken hypershift, and it is no longer installing.  Hypershift fails on
```
error is version False True 30m Unable to apply 4.14.0-0.nightly-2023-08-25-105956: the cluster operator kube-storage-version-migrator is not available
```
It seems the deployment never succeeds:
```
- lastTransitionTime: "2023-08-25T11:27:43Z"
message: 'KubeStorageVersionMigratorProgressing: Waiting for Deployment to deploy
pods'
reason: KubeStorageVersionMigrator_Deploying
status: "True" …
```
> Revert "specify master node selector on migrator pod"

- .ci-operator.yaml
- go.mod
- go.sum
- images/ci/Dockerfile
replaces https://github.com/openshift/cluster-kube-storage-version-migrator-operator/pull/102 which fails `verify-deps` job with `on go.sum content is incorrect - did you run go mod tidy?`
> OCPBUGS-27930: Updating ose-cluster-kube-storage-version-migrator-operator-container image to be consistent with ART for 4.16

- manifests/01_storage_migration_crd.yaml
- manifests/01_storage_state_crd.yaml
- manifests/02_namespace.yaml
- manifests/03_configmap.yaml
- manifests/04_serviceaccount.yaml
- manifests/05_roles.yaml
- manifests/06_operatorconfig.yaml
- manifests/07_deployment-ibm-cloud-managed.yaml
- manifests/08_service.yaml
- manifests/09_clusteroperator.yaml
- profile-patches/ibm-cloud-managed/07_deployment.yaml-patch
Since HyperShift / Hosted Control Plane have adopted include.release.openshift.io/ibm-cloud-managed, to tailor the resources of clusters running in the ROKS IBM environment, the include.release.openshift.io/hypershift addition will allow Hypershift to express different profile choices than ROKS
> OCPBUGS-29567: Apply hypershift cluster-profile for ibm-cloud-managed

- bindata/kube-storage-version-migrator/deployment.yaml
- manifests/07_deployment-ibm-cloud-managed.yaml
- manifests/07_deployment.yaml
[OCPBUGS-36322](https://issues.redhat.com/browse/OCPBUGS-36322
)
Manual cherry-pick of [#107](https://github.com/openshift/cluster-kube-storage-version-migrator-operator/pull/107)
> [release-4.15] OCPBUGS-36322: Set required-scc for openshift workloads

- pkg/operator/starter.go
termination is a normal operation and shouldn't cause any errors. the library-go framework might interpret errors and exit prematurely.
note that this fix does not make the operator exit gracefully. 
this fix will also not make [the operator release the lease gracefully.](https://github.com/openshift/cluster-kube-apiserver-operator/blob/5b21d79597009195978c3746d0fb15bd2103525b/vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go#L392)
@deads2k since the lease is acquired by the lib-go code I think we could ensure it would wait until the lease was cleaned up.
> NO-JIRA: operator/starter.go: don't report an error on shutdown

- bindata/kube-storage-version-migrator/deployment.yaml
- pkg/operator/deploymentcontroller/deployment.go
- pkg/operator/deploymentcontroller/deployment_test.go
Add a sidecar container that, in combination with an appropriate `terminationGracePeriodSeconds` setting on the pod, keeps a terminating pod around until its replacement pod is ready.
> OCPBUGS-20062: "gracefully" shutdown KSVM pod. 
